<a href="https://colab.research.google.com/github/Trusha216/T216/blob/main/house_prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv('house_prices.csv')
data

<ipython-input-1-a414bc8c991c>:3: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('house_prices.csv')

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106532,106532,3 BHK Ready to Occupy Flat for sale in Urban H...,This ready to move unit is available for sale ...,1.20 Cr,7737.0,kolkata,NaN,Ready to Move,2 out of 7,New Property,...,North - East,NaN,Urban Heights,2.0,2.0,1 Covered,Freehold,1551 sqft,NaN,NaN
106533,106533,3 BHK Ready to Occupy Flat for sale in Elita G...,3BHK with 1956 sqft flat available for sale in...,1.21 Cr,6189.0,kolkata,1450 sqft,Ready to Move,18 out of 28,Resale,...,North - East,Garden/Park,Elita Garden Vista,3.0,2.0,1 Covered,Freehold,NaN,NaN,NaN
106534,106534,3 BHK Ready to Occupy Flat for sale in Rare Ea...,"As dusk falls, joy wakes anew at the Rare Eart...",1.92 Cr,10614.0,kolkata,NaN,Ready to Move,4 out of 35,New Property,...,West,Garden/Park,Rare Earth,3.0,1.0,1 Covered,Freehold,1809 sqft,NaN,NaN
106535,106535,2 BHK Ready to Occupy Flat for sale Nayabad,"2 BHK, Multistorey Apartment is available for ...",25 Lac,NaN,kolkata,750 sqft,Ready to Move,Ground out of 2,Resale,...,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN
106536,106536,2 BHK Ready to Occupy Flat for sale Maheshtala,Multistorey ap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [ ]:
data.tail()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
106532,106532,3 BHK Ready to Occupy Flat for sale in Urban H...,This ready to move unit is available for sale ...,1.20 Cr,7737.0,kolkata,NaN,Ready to Move,2 out of 7,New Property,...,North - East,NaN,Urban Heights,2.0,2.0,1 Covered,Freehold,1551 sqft,NaN,NaN
106533,106533,3 BHK Ready to Occupy Flat for sale in Elita G...,3BHK with 1956 sqft flat available for sale in...,1.21 Cr,6189.0,kolkata,1450 sqft,Ready to Move,18 out of 28,Resale,...,North - East,Garden/Park,Elita Garden Vista,3.0,2.0,1 Covered,Freehold,NaN,NaN,NaN
106534,106534,3 BHK Ready to Occupy Flat for sale in Rare Ea...,"As dusk falls, joy wakes anew at the Rare Eart...",1.92 Cr,10614.0,kolkata,NaN,Ready to Move,4 out of 35,New Property,...,West,Garden/Park,Rare Earth,3.0,1.0,1 Covered,Freehold,1809 sqft,NaN,NaN
106535,106535,2 BHK Ready to Occupy Flat for sale Nayabad,"2 BHK, Multistorey Apartment is available for ...",25 Lac,NaN,kolkata,750 sqft,Ready to Move,Ground out of 2,Resale,...,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN
106536,106536,2 BHK Ready to Occupy Flat for sale Maheshtala,Multistorey ap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.shape

(106537, 21)

In [ ]:
"""Index – A unique identifier for each property listing.
Title – The headline or summary of the property listing.
Description – A detailed textual description of the property.
Amount (in rupees) – The total price of the property in Indian rupees (with units like "Lac" or "Cr").
Price (in rupees) – The per-square-foot price of the property.
Location – The city or area where the property is located.
Carpet Area – The usable floor area of the property (excluding walls, balconies, etc.).
Status – The current state of the property (e.g., "Ready to Move").
Floor – The floor number where the flat is located (e.g., "10 out of 11").
Transaction – Indicates whether the property is a resale or a new sale.
Furnishing – The furnishing status (e.g., "Furnished," "Semi-Furnished," or "Unfurnished").
Facing – The direction the property faces (e.g., East, West).
Overlooking – The type of view from the property (e.g., Garden/Park, Main Road).
Society – The name of the residential society or building.
Bathroom – The number of bathrooms in the property.
Balcony – The number of balconies.
Car Parking – The type of parking available (e.g., "1 Covered," "1 Open").
Ownership – The type of property ownership (e.g., Freehold, Leasehold).
Super Area – The total built-up area including common spaces.
Dimensions – The dimensions of the property (if available).
Plot Area – The total land area (if applicable)"""

data.columns

Index(['Index', 'Title', 'Description', 'Amount(in rupees)',
       'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor',
       'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area',
       'Dimensions', 'Plot Area'],
      dtype='object')

In [ ]:
data.isna().sum()

Index                     0
Title                     0
Description            2303
Amount(in rupees)         1
Price (in rupees)     10051
location                  1
Carpet Area           53091
Status                  360
Floor                  5016
Transaction              39
Furnishing             2076
facing                41917
overlooking           50362
Society               68227
Bathroom                428
Balcony               32182
Car Parking           60155
Ownership             41126
Super Area            54188
Dimensions           106537
Plot Area            106537
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106537 entries, 0 to 106536
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              106537 non-null  int64
 1   Title              106537 non-null  object
 2   Description        104234 non-null  object
 3   Amount(in rupees)  106536 non-null  object
 4   Price (in rupees)  96486 non-null   float64
 5   location           106536 non-null  object
 6   Carpet Area        53446 non-null   object
 7   Status             106177 non-null  object
 8   Floor              101521 non-null  object
 9   Transaction        106498 non-null  object
 10  Furnishing         104461 non-null  object
 11  facing             64620 non-null   object
 12  overlooking        56175 non-null   object
 13  Society            38310 non-null   object
 14  Bathroom           106109 non-null  object
 15  Balcony            74355 non-null   object
 16  Car Parking        46382 non-null   object
 17  Ownership          65411 non-null   object
 18  Super Area         52349 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 17.1+ MB

In [ ]:
data.describe()

               Index  Price (in rupees)  Dimensions  Plot Area
count  106537.000000       96486.000000         0.0        0.0
mean    53268.000000        7403.650623         NaN        NaN
std     30754.727152        4549.637675         NaN        NaN
min         0.000000          17.000000         NaN        NaN
25%     26634.000000        4602.000000         NaN        NaN
50%     53268.000000        6173.000000         NaN        NaN
75%     79902.000000        8367.000000         NaN        NaN
max    106536.000000       84619.000000         NaN        NaN

In [ ]:
data.rename(columns={"Carpet Area": "Carpet Area (in sqft)"}, inplace=True)

In [ ]:
data.rename(columns={"Super Area": "Super Area (in sqft)"}, inplace=True)

In [ ]:
data["Carpet Area (in sqft)"] = data["Carpet Area (in sqft)"].str.replace(" sqft", "", regex=True)
data["Carpet Area (in sqft)"] = pd.to_numeric(data["Carpet Area (in sqft)"], errors="coerce")

# Display updated DataFrame
print(data.head())

   Index                                              Title  \
0      0  1 BHK Ready to Occupy Flat for sale in Srushti...
1      1  2 BHK Ready to Occupy Flat for sale in Dosti V...
2      2  2 BHK Ready to Occupy Flat for sale in Sunrise...
3      3        1 BHK Ready to Occupy Flat for sale Kasheli
4      4  2 BHK Ready to Occupy Flat for sale in TenX Ha...

                                         Description Amount(in rupees)  \
0  Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac
1  One can find this stunning 2 BHK flat for sale...           98 Lac
2  Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr
3  This beautiful 1 BHK Flat is available for sal...           25 Lac
4  This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr

   Price (in rupees) location  Carpet Area (in sqft)         Status  \
0             6000.0    thane                  500.0  Ready to Move
1            13799.0    thane                  473.0  Ready to Move
2            17500.0    thane                  779.0  Ready to Move
3                NaN    thane                  530.0  Ready to Move
4            18824.0    thane                  635.0  Ready to Move

          Floor Transaction  ... facing             overlooking  \
0  10 out of 11      Resale  ...    NaN                     NaN
1   3 out of 22      Resale  ...   East             Garden/Park
2  10 out of 29      Resale  ...   East             Garden/Park
3    1 out of 3      Resale  ...    NaN                     NaN
4  20 out of 42      Resale  ...   West  Garden/Park, Main Road

                               Society Bathroom Balcony Car Parking  \
0  Srushti Siddhi Mangal Murti Complex        1       2         NaN
1                          Dosti Vihar        2     NaN      1 Open
2                 Sunrise by Kalpataru        2     NaN   1 Covered
3                                  NaN        1       1         NaN
4          TenX Habitat Raymond Realty        2     NaN   1 Covered

              Ownership Super Area (in sqft) Dimensions  Plot Area
0                   NaN                  NaN        NaN        NaN
1              Freehold                  NaN        NaN        NaN
2              Freehold                  NaN        NaN        NaN
3                   NaN                  NaN        NaN        NaN
4  Co-operative Society                  NaN        NaN        NaN

[5 rows x 21 columns]

In [ ]:
data["Super Area (in sqft)"] = data["Super Area (in sqft)"].astype(str).str.replace(" sqft", "", regex=True)
data["Super Area (in sqft)"] = pd.to_numeric(data["Super Area (in sqft)"], errors="coerce")

print(data.head())  # Check the updated DataFrame

   Index                                              Title  \
0      0  1 BHK Ready to Occupy Flat for sale in Srushti...
1      1  2 BHK Ready to Occupy Flat for sale in Dosti V...
2      2  2 BHK Ready to Occupy Flat for sale in Sunrise...
3      3        1 BHK Ready to Occupy Flat for sale Kasheli
4      4  2 BHK Ready to Occupy Flat for sale in TenX Ha...

                                         Description Amount(in rupees)  \
0  Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac
1  One can find this stunning 2 BHK flat for sale...           98 Lac
2  Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr
3  This beautiful 1 BHK Flat is available for sal...           25 Lac
4  This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr

   Price (in rupees) location  Carpet Area (in sqft)         Status  \
0             6000.0    thane                  500.0  Ready to Move
1            13799.0    thane                  473.0  Ready to Move
2            17500.0    thane                  779.0  Ready to Move
3                NaN    thane                  530.0  Ready to Move
4            18824.0    thane                  635.0  Ready to Move

          Floor Transaction  ... facing             overlooking  \
0  10 out of 11      Resale  ...    NaN                     NaN
1   3 out of 22      Resale  ...   East             Garden/Park
2  10 out of 29      Resale  ...   East             Garden/Park
3    1 out of 3      Resale  ...    NaN                     NaN
4  20 out of 42      Resale  ...   West  Garden/Park, Main Road

                               Society Bathroom Balcony Car Parking  \
0  Srushti Siddhi Mangal Murti Complex        1       2         NaN
1                          Dosti Vihar        2     NaN      1 Open
2                 Sunrise by Kalpataru        2     NaN   1 Covered
3                                  NaN        1       1         NaN
4          TenX Habitat Raymond Realty        2     NaN   1 Covered

              Ownership Super Area (in sqft)  Dimensions  Plot Area
0                   NaN                  NaN         NaN        NaN
1              Freehold                  NaN         NaN        NaN
2              Freehold                  NaN         NaN        NaN
3                   NaN                  NaN         NaN        NaN
4  Co-operative Society                  NaN         NaN        NaN

[5 rows x 21 columns]

In [ ]:
data["Open car Parking"] = data["Car Parking"].str.extract(r'(\d+)\s*Open')

data["Covered car Parking"] = data["Car Parking"].str.extract(r'(\d+)\s*Covered')

data["Open car Parking"] = pd.to_numeric(data["Open car Parking"], errors="coerce").fillna(0)
data["Covered car Parking"] = pd.to_numeric(data["Covered car Parking"], errors="coerce").fillna(0)

In [ ]:
data.head(10)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area (in sqft),Status,Floor,Transaction,...,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area (in sqft),Dimensions,Plot Area,Open car Parking,Covered car Parking
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500.0,Ready to Move,10 out of 11,Resale,...,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473.0,Ready to Move,3 out of 22,Resale,...,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,1.0,0.0
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779.0,Ready to Move,10 out of 29,Resale,...,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530.0,Ready to Move,1 out of 3,Resale,...,NaN,1,1,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635.0,Ready to Move,20 out of 42,Resale,...,TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,0.0,1.0
5,5,1 BHK Ready to Occupy Flat for sale in Virat A...,Creatively planned and constructed is a 1 BHK ...,45 Lac,6618.0,thane,NaN,Ready to Move,2 out of 7,Resale,...,Virat Aangan,1,1,NaN,Co-operative Society,680.0,NaN,NaN,0.0,0.0
6,6,1 BHK Ready to Occupy Flat for sale Mumbra,This magnificent 1 BHK Flat is available for s...,16.5 Lac,2538.0,thane,550.0,Ready to Move,4 out of 5,Resale,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
7,7,1 BHK Ready to Occupy Flat for sale Kalwa,Creatively planned and constructed is a 1 BHK ...,60 Lac,10435.0,thane,NaN,Ready to Move,Ground out of 7,Resale,...,NaN,1,NaN,NaN,NaN,575.0,NaN,NaN,0.0,0.0
8,8,1 BHK Ready to Occupy Flat for sale Kalwa,Discover this immaculate 1 BHK flat for sale a...,60 Lac,10000.0,thane,NaN,Ready to Move,Ground out of 2,Resale,...,NaN,1,NaN,NaN,Co-operative Society,600.0,NaN,NaN,0.0,0.0
9,9,3 BHK Ready to Occupy Flat for sale in Pride P...,One can find this stunning 3 BHK flat for sale...,1.60 Cr,11150.0,thane,900.0,Ready to Move,3 out of 27,Resale,...,Pride Palms,3,1,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0

In [ ]:
import pandas as pd
import numpy as np
floor_data = data['Floor']

current_floor = []
total_floors = []

for entry in floor_data:
    if isinstance(entry, str) and " out of " in entry:
        parts = entry.split(" out of ")
        floor = parts[0].strip()
        total = parts[1].strip()


        if floor.lower() == "ground":
            current_floor.append(0)
        elif floor.lower() == "upper basement":
            current_floor.append(-1)
        elif floor.lower() == "lower basement":
            current_floor.append(-2)
        else:
            try:
                current_floor.append(int(floor))
            except ValueError:
                current_floor.append(np.nan)


        try:
            total_floors.append(int(total))
        except ValueError:
            total_floors.append(np.nan)
    else:

        current_floor.append(np.nan)
        total_floors.append(np.nan)


df = pd.DataFrame({"Current Floor": current_floor, "Total Floors": total_floors})


print(df)

        Current Floor  Total Floors
0                10.0          11.0
1                 3.0          22.0
2                10.0          29.0
3                 1.0           3.0
4                20.0          42.0
...               ...           ...
106532            2.0           7.0
106533           18.0          28.0
106534            4.0          35.0
106535            0.0           2.0
106536            NaN           NaN

[106537 rows x 2 columns]

In [ ]:
df = pd.DataFrame({"Current Floor": current_floor, "Total Floors": total_floors})
df.to_csv("house_prices.csv", mode='a', index=False, header=False)

In [ ]:
data["Current Floor"] = current_floor
data["Total Floors"] = total_floors

data.to_csv("house_prices.csv", index=False)

In [ ]:
print(len(data))
print(len(current_floor))
print(len(total_floors))

106537
106537
106537

In [ ]:
data.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area (in sqft),Status,Floor,Transaction,...,Balcony,Car Parking,Ownership,Super Area (in sqft),Dimensions,Plot Area,Open car Parking,Covered car Parking,Current Floor,Total Floors
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500.0,Ready to Move,10 out of 11,Resale,...,2,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10.0,11.0
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473.0,Ready to Move,3 out of 22,Resale,...,NaN,1 Open,Freehold,NaN,NaN,NaN,1.0,0.0,3.0,22.0
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779.0,Ready to Move,10 out of 29,Resale,...,NaN,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0,10.0,29.0
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530.0,Ready to Move,1 out of 3,Resale,...,1,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,3.0
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635.0,Ready to Move,20 out of 42,Resale,...,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,0.0,1.0,20.0,42.0

In [ ]:
data.tail()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area (in sqft),Status,Floor,Transaction,...,Balcony,Car Parking,Ownership,Super Area (in sqft),Dimensions,Plot Area,Open car Parking,Covered car Parking,Current Floor,Total Floors
106532,106532,3 BHK Ready to Occupy Flat for sale in Urban H...,This ready to move unit is available for sale ...,1.20 Cr,7737.0,kolkata,NaN,Ready to Move,2 out of 7,New Property,...,2.0,1 Covered,Freehold,1551.0,NaN,NaN,0.0,1.0,2.0,7.0
106533,106533,3 BHK Ready to Occupy Flat for sale in Elita G...,3BHK with 1956 sqft flat available for sale in...,1.21 Cr,6189.0,kolkata,1450.0,Ready to Move,18 out of 28,Resale,...,2.0,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0,18.0,28.0
106534,106534,3 BHK Ready to Occupy Flat for sale in Rare Ea...,"As dusk falls, joy wakes anew at the Rare Eart...",1.92 Cr,10614.0,kolkata,NaN,Ready to Move,4 out of 35,New Property,...,1.0,1 Covered,Freehold,1809.0,NaN,NaN,0.0,1.0,4.0,35.0
106535,106535,2 BHK Ready to Occupy Flat for sale Nayabad,"2 BHK, Multistorey Apartment is available for ...",25 Lac,NaN,kolkata,750.0,Ready to Move,Ground out of 2,Resale,...,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,2.0
106536,106536,2 BHK Ready to Occupy Flat for sale Maheshtala,Multistorey ap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN

In [ ]:
data.rename(columns={"Amount(in rupees)": "Amount(in lac)"}, inplace=True)

In [ ]:
def convert_cr_to_lac(amount):
    if isinstance(amount, str):
        amount = amount.strip()
        if "Cr" in amount:
            value = float(amount.replace("Cr", "").strip())
            return f"{value * 100} Lac"
        elif "Lac" in amount:
            return amount  # Already in Lac
        elif "Call for Price" in amount:
            return amount  # Keep as is
    return "Invalid Input"

# Example Usage:
amounts =data['Amount(in lac)']
converted_amounts = [convert_cr_to_lac(a) for a in amounts]

In [ ]:
data["converted_amounts"] = converted_amounts
data.to_csv("house_prices.csv", index=False)

In [ ]:
data.head()

,Index,Title,Description,Amount(in lac),Price (in rupees),location,Carpet Area (in sqft),Status,Floor,Transaction,...,Car Parking,Ownership,Super Area (in sqft),Dimensions,Plot Area,Open car Parking,Covered car Parking,Current Floor,Total Floors,converted_amounts
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500.0,Ready to Move,10 out of 11,Resale,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10.0,11.0,42 Lac
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473.0,Ready to Move,3 out of 22,Resale,...,1 Open,Freehold,NaN,NaN,NaN,1.0,0.0,3.0,22.0,98 Lac
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779.0,Ready to Move,10 out of 29,Resale,...,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0,10.0,29.0,140.0 Lac
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530.0,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,3.0,25 Lac
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635.0,Ready to Move,20 out of 42,Resale,...,1 Covered,Co-operative Society,NaN,NaN,NaN,0.0,1.0,20.0,42.0,160.0 Lac

In [ ]:
data.tail()

,Index,Title,Description,Amount(in lac),Price (in rupees),location,Carpet Area (in sqft),Status,Floor,Transaction,...,Car Parking,Ownership,Super Area (in sqft),Dimensions,Plot Area,Open car Parking,Covered car Parking,Current Floor,Total Floors,converted_amounts
106532,106532,3 BHK Ready to Occupy Flat for sale in Urban H...,This ready to move unit is available for sale ...,1.20 Cr,7737.0,kolkata,NaN,Ready to Move,2 out of 7,New Property,...,1 Covered,Freehold,1551.0,NaN,NaN,0.0,1.0,2.0,7.0,120.0 Lac
106533,106533,3 BHK Ready to Occupy Flat for sale in Elita G...,3BHK with 1956 sqft flat available for sale in...,1.21 Cr,6189.0,kolkata,1450.0,Ready to Move,18 out of 28,Resale,...,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0,18.0,28.0,121.0 Lac
106534,106534,3 BHK Ready to Occupy Flat for sale in Rare Ea...,"As dusk falls, joy wakes anew at the Rare Eart...",1.92 Cr,10614.0,kolkata,NaN,Ready to Move,4 out of 35,New Property,...,1 Covered,Freehold,1809.0,NaN,NaN,0.0,1.0,4.0,35.0,192.0 Lac
106535,106535,2 BHK Ready to Occupy Flat for sale Nayabad,"2 BHK, Multistorey Apartment is available for ...",25 Lac,NaN,kolkata,750.0,Ready to Move,Ground out of 2,Resale,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,2.0,25 Lac
106536,106536,2 BHK Ready to Occupy Flat for sale Maheshtala,Multistorey ap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Invalid Input

In [ ]:
!pip install dvc[gdrive]

Collecting dvc[gdrive]
  Downloading dvc-3.59.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (25.1.0)
Collecting celery (from dvc[gdrive])
  Downloading celery-5.4.0-py3-none-any.whl.metadata (21 kB)
Collecting colorama>=0.3.9 (from dvc[gdrive])
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting configobj>=5.0.9 (from dvc[gdrive])
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (1.9.0)
Collecting dpath<3,>=2.1.0 (from dvc[gdrive])
  Downloading dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Collecting dulwich (from dvc[gdrive])
  Downloading dulwich-0.22.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Collecting dvc-data<3.17,>=3.16.2 (from dvc[gdrive])
  Downloading dvc_data-3.16.9-py3-none-any.whl.metadata (5.0 kB)
Collecting dvc-http>=2.29.0 (from dvc[gdrive])
  Downloading dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Collecting dvc-objects (from dvc[gdrive])
  Downloading dvc_objects-5.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting dvc-render<2,>=1.0.1 (from dvc[gdrive])
  Downloading dvc_render-1.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dvc-studio-client<1,>=0.21 (from dvc[gdrive])
  Downloading dvc_studio_client-0.21.0-py3-none-any.whl.metadata (4.3 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc[gdrive])
  Downloading dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Collecting flatten_dict<1,>=0.4.1 (from dvc[gdrive])
  Downloading flatten_dict-0.4.2-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting flufl.lock<9,>=8.1.0 (from dvc[gdrive])
  Downloading flufl_lock-8.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (2024.10.0)
Collecting funcy>=1.14 (from dvc[gdrive])
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting grandalf<1,>=0.7 (from dvc[gdrive])
  Downloading grandalf-0.8-py3-none-any.whl.metadata (1.7 kB)
Collecting gto<2,>=1.6.0 (from dvc[gdrive])
  Downloading gto-1.7.2-py3-none-any.whl.metadata (4.7 kB)
Collecting hydra-core>=1.1 (from dvc[gdrive])
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc[gdrive])
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting kombu (from dvc[gdrive])
  Downloading kombu-5.4.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (3.4.2)
Collecting omegaconf (from dvc[gdrive])
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: packaging>=19 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (24.2)
Collecting pathspec>=0.10.3 (from dvc[gdrive])
  Downloading pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (4.3.6)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (3.0.4)
Collecting pygtrie>=2.3.2 (from dvc[gdrive])
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (3.2.1)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (2.32.3)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (13.9.4)
Collecting ruamel.yaml>=0.17.11 (from dvc[gdrive])
  Downloading ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)
Collecting scmrepo<4,>=3.3.8 (from dvc[gdrive])
  Downloading scmrepo-3.3.10-py3-none-any.whl.metadata (4.8 kB)
Collecting shortuuid>=0.5 (from dvc[gdrive])
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting shtab<2,>=1.3.4 (from dvc[gdrive])
  Downloading shtab-1.7.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (0.9.0)
Collecting tomlkit>=0.11.1 (from dvc[gdrive])
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.11/dist-packages (from dvc[gdrive]) (4.67.1)
Collecting voluptuous>=0.11.7 (from dvc[gdrive])
  Downloading voluptuous-0.15.2-py3-none-any.whl.metadata (20 kB)
Collecting zc.lockfile>=1.2.1 (from dvc[gdrive])
  Downloading zc.lockfile-3.0.post1-py3-none-any.whl.metadata (6.2 kB)
Collecting dvc-gdrive<4,>=3 (from dvc[gdrive])
  Downloading dvc_gdrive-3.0.1-py3-none-any.whl.metadata (2.1 kB)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.17,>=3.16.2->dvc[gdrive])
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.17,>=3.16.2->dvc[gdrive])
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.17,>=3.16.2->dvc[gdrive])
  Downloading sqltrie-0.11.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.11/dist-packages (from dvc-data<3.17,>=3.16.2->dvc[gdrive]) (3.10.15)
Requirement already satisfied: pydrive2>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (1.21.3)
Collecting aiohttp-retry>=2.5.0 (from dvc-http>=2.29.0->dvc[gdrive])
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Collecting billiard<5.0,>=4.2.0 (from celery->dvc[gdrive])
  Downloading billiard-4.2.1-py3-none-any.whl.metadata (4.4 kB)
Collecting vine<6.0,>=5.1.0 (from celery->dvc[gdrive])
  Downloading vine-5.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.11/dist-packages (from celery->dvc[gdrive]) (8.1.8)
Collecting click-didyoumean>=0.3.0 (from celery->dvc[gdrive])
  Downloading click_didyoumean-0.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting click-repl>=0.2.0 (from celery->dvc[gdrive])
  Downloading click_repl-0.3.0-py3-none-any.whl.metadata (3.6 kB)
Collecting click-plugins>=1.1.1 (from celery->dvc[gdrive])
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from celery->dvc[gdrive]) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from celery->dvc[gdrive]) (2.8.2)
Requirement already satisfied: six<2.0,>=1.12 in /usr/local/lib/python3.11/dist-packages (from flatten_dict<1,>=0.4.1->dvc[gdrive]) (1.17.0)
Requirement already satisfied: atpublic in /usr/local/lib/python3.11/dist-packages (from flufl.lock<9,>=8.1.0->dvc[gdrive]) (4.1.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc[gdrive]) (0.4)
Requirement already satisfied: pydantic!=2.0.0,<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc[gdrive]) (2.10.6)
Collecting semver>=2.13.0 (from gto<2,>=1.6.0->dvc[gdrive])
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: typer>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gto<2,>=1.6.0->dvc[gdrive]) (0.15.1)
Collecting antlr4-python3-runtime==4.9.* (from hydra-core>=1.1->dvc[gdrive])
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting appdirs (from iterative-telemetry>=0.0.7->dvc[gdrive])
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from iterative-telemetry>=0.0.7->dvc[gdrive]) (3.17.0)
Collecting amqp<6.0.0,>=5.1.1 (from kombu->dvc[gdrive])
  Downloading amqp-5.3.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from omegaconf->dvc[gdrive]) (6.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22->dvc[gdrive]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22->dvc[gdrive]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22->dvc[gdrive]) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.22->dvc[gdrive]) (2025.1.31)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=12->dvc[gdrive]) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=12->dvc[gdrive]) (2.18.0)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.17.11->dvc[gdrive])
  Downloading ruamel.yaml.clib-0.2.12-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: gitpython>3 in /usr/local/lib/python3.11/dist-packages (from scmrepo<4,>=3.3.8->dvc[gdrive]) (3.1.44)
Requirement already satisfied: pygit2>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from scmrepo<4,>=3.3.8->dvc[gdrive]) (1.17.0)
Collecting asyncssh<3,>=2.13.1 (from scmrepo<4,>=3.3.8->dvc[gdrive])
  Downloading asyncssh-2.20.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from zc.lockfile>=1.2.1->dvc[gdrive]) (75.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (3.11.12)
Requirement already satisfied: cryptography>=39.0 in /usr/local/lib/python3.11/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.3.8->dvc[gdrive]) (43.0.3)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.3.8->dvc[gdrive]) (4.12.2)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /usr/local/lib/python3.11/dist-packages (from click-repl>=0.2.0->celery->dvc[gdrive]) (3.0.50)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython>3->scmrepo<4,>=3.3.8->dvc[gdrive]) (4.0.12)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=12->dvc[gdrive]) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=2.0.0,<3,>=1.9.0->gto<2,>=1.6.0->dvc[gdrive]) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=2.0.0,<3,>=1.9.0->gto<2,>=1.6.0->dvc[gdrive]) (2.27.2)
Requirement already satisfied: google-api-python-client>=1.12.5 in /usr/local/lib/python3.11/dist-packages (from pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (2.160.0)
Requirement already satisfied: oauth2client>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.1.3)
Requirement already satisfied: pyOpenSSL<=24.2.1,>=19.1.0 in /usr/local/lib/python3.11/dist-packages (from pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (24.2.1)
Requirement already satisfied: cffi>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from pygit2>=1.14.0->scmrepo<4,>=3.3.8->dvc[gdrive]) (1.17.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.4.1->gto<2,>=1.6.0->dvc[gdrive]) (1.5.4)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (1.3.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc[gdrive]) (1.18.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.17.0->pygit2>=1.14.0->scmrepo<4,>=3.3.8->dvc[gdrive]) (2.22)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.3.8->dvc[gdrive]) (5.0.2)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (2.27.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.2.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (2.24.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.1.1)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.11/dist-packages (from oauth2client>=4.0.0->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.6.1)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.11/dist-packages (from oauth2client>=4.0.0->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (0.4.1)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from oauth2client>=4.0.0->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.9)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc[gdrive]) (0.2.13)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (1.67.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (4.25.6)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (1.26.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client>=1.12.5->pydrive2>=1.19.0->pydrive2[fsspec]>=1.19.0->dvc-gdrive<4,>=3->dvc[gdrive]) (5.5.1)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading dpath-2.2.0-py3-none-any.whl (17 kB)
Downloading dvc_data-3.16.9-py3-none-any.whl (77 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.2/77.2 kB 6.8 MB/s eta 0:00:00
Downloading dvc_gdrive-3.0.1-py3-none-any.whl (11 kB)
Downloading dvc_http-2.32.0-py3-none-any.whl (12 kB)
Downloading dvc_objects-5.1.0-py3-none-any.whl (33 kB)
Downloading dvc_render-1.0.2-py3-none-any.whl (22 kB)
Downloading dvc_studio_client-0.21.0-py3-none-any.whl (16 kB)
Downloading dvc_task-0.40.2-py3-none-any.whl (21 kB)
Downloading celery-5.4.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 426.0/426.0 kB 30.2 MB/s eta 0:00:00
Downloading flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Downloading flufl_lock-8.1.0-py3-none-any.whl (11 kB)
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Downloading grandalf-0.8-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.4 MB/s eta 0:00:00
Downloading gto-1.7.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 4.1 MB/s eta 0:00:00
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 13.1 MB/s eta 0:00:00
Downloading iterative_telemetry-0.0.10-py3-none-any.whl (10 kB)
Downloading kombu-5.4.2-py3-none-any.whl (201 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 kB 18.3 MB/s eta 0:00:00
Downloading vine-5.1.0-py3-none-any.whl (9.6 kB)
Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.7 MB/s eta 0:00:00
Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Downloading ruamel.yaml-0.18.10-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.7/117.7 kB 11.3 MB/s eta 0:00:00
Downloading scmrepo-3.3.10-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.7/73.7 kB 6.9 MB/s eta 0:00:00
Downloading dulwich-0.22.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (979 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 979.7/979.7 kB 52.4 MB/s eta 0:00:00
Downloading shortuuid-1.0.13-py3-none-any.whl (10 kB)
Downloading shtab-1.7.1-py3-none-any.whl (14 kB)
Downloading tomlkit-0.13.2-py3-none-any.whl (37 kB)
Downloading voluptuous-0.15.2-py3-none-any.whl (31 kB)
Downloading zc.lockfile-3.0.post1-py3-none-any.whl (9.8 kB)
Downloading dvc-3.59.1-py3-none-any.whl (457 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.7/457.7 kB 34.5 MB/s eta 0:00:00
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading amqp-5.3.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 4.5 MB/s eta 0:00:00
Downloading asyncssh-2.20.0-py3-none-any.whl (373 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 373.1/373.1 kB 30.5 MB/s eta 0:00:00
Downloading billiard-4.2.1-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.2 MB/s eta 0:00:00
Downloading click_didyoumean-0.3.1-py3-none-any.whl (3.6 kB)
Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Downloading click_repl-0.3.0-py3-none-any.whl (10 kB)
Downloading dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)

In [ ]:
!git config --global user.email "trusha@7span.com"
!git config --global user.name "Trusha"

In [ ]:
!git init  # Initialize Git if not already
!dvc init  # Initialize DVC in your project
!git commit -m "Initialize DVC"

Reinitialized existing Git repository in /content/.git/
ERROR: failed to initiate DVC - '.dvc' exists. Use `-f` to force.
[master (root-commit) 27e4a5b] Initialize DVC
 3 files changed, 6 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvcignore

In [ ]:
!dvc add dataset.csv
!git add dataset.csv.dvc .gitignore
!git commit -m "house_prices.csv with DVC"

⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
ERROR: output 'dataset.csv' does not exist: [Errno 2] No such file or directory: '/content/dataset.csv'
fatal: pathspec 'dataset.csv.dvc' did not match any files
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .dvc/config

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	house_prices.csv
	sample_data/

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
!dvc remote add -d myremote gdrive://your_drive_folder_id
!git commit .dvc/config -m "Configure Google Drive remote"

Setting 'myremote' as a default remote.
ERROR: configuration error - config file error: remote 'myremote' already exists. Use `-f|--force` to overwrite it.
[master b9b6887] Configure Google Drive remote
 1 file changed, 4 insertions(+)

In [ ]:
!dvc push

Collecting          |0.00 [00:00,    ?entry/s]
Pushing
Everything is up to date.

In [ ]:
!dvc pull

Collecting          |0.00 [00:00,    ?entry/s]
Fetching
Building workspace index          |0.00 [00:00,    ?entry/s]
Comparing indexes          |1.00 [00:00, 3.19kentry/s]
Applying changes          |0.00 [00:00,     ?file/s]
Everything is up to date.

In [ ]:
!git checkout <commit_hash>
!dvc checkout

/bin/bash: -c: line 1: syntax error near unexpected token `newline'
/bin/bash: -c: line 1: `git checkout <commit_hash>'
Building workspace index          |0.00 [00:00,    ?entry/s]
Comparing indexes          |1.00 [00:00, 3.34kentry/s]
Applying changes          |0.00 [00:00,     ?file/s]

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
data=pd.read_csv('house_prices.csv')
data

<ipython-input-15-b77545eca52c>:1: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('house_prices.csv')

,Index,Title,Description,Amount(in lac),Price (in rupees),location,Carpet Area (in sqft),Status,Floor,Transaction,...,Car Parking,Ownership,Super Area (in sqft),Dimensions,Plot Area,Open car Parking,Covered car Parking,Current Floor,Total Floors,converted_amounts
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500.0,Ready to Move,10 out of 11,Resale,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10.0,11.0,42 Lac
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473.0,Ready to Move,3 out of 22,Resale,...,1 Open,Freehold,NaN,NaN,NaN,1.0,0.0,3.0,22.0,98 Lac
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779.0,Ready to Move,10 out of 29,Resale,...,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0,10.0,29.0,140.0 Lac
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530.0,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,3.0,25 Lac
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635.0,Ready to Move,20 out of 42,Resale,...,1 Covered,Co-operative Society,NaN,NaN,NaN,0.0,1.0,20.0,42.0,160.0 Lac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106532,106532,3 BHK Ready to Occupy Flat for sale in Urban H...,This ready to move unit is available for sale ...,1.20 Cr,7737.0,kolkata,NaN,Ready to Move,2 out of 7,New Property,...,1 Covered,Freehold,1551.0,NaN,NaN,0.0,1.0,2.0,7.0,120.0 Lac
106533,106533,3 BHK Ready to Occupy Flat for sale in Elita G...,3BHK with 1956 sqft flat available for sale in...,1.21 Cr,6189.0,kolkata,1450.0,Ready to Move,18 out of 28,Resale,...,1 Covered,Freehold,NaN,NaN,NaN,0.0,1.0,18.0,28.0,121.0 Lac
106534,106534,3 BHK Ready to Occupy Flat for sale in Rare Ea...,"As dusk falls, joy wakes anew at the Rare Eart...",1.92 Cr,10614.0,kolkata,NaN,Ready to Move,4 out of 35,New Property,...,1 Covered,Freehold,1809.0,NaN,NaN,0.0,1.0,4.0,35.0,192.0 Lac
106535,106535,2 BHK Ready to Occupy Flat for sale Nayabad,"2 BHK, Multistorey Apartment is available for ...",25 Lac,NaN,kolkata,750.0,Ready to Move,Ground out of 2,Resale,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,2.0,25 Lac
106536,106536,2 BHK Ready to Occupy Flat for sale Maheshtala,Multistorey ap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Invalid Input